### ISSUE TITLE
pacman -Sy  returned error: s3.amazonaws.com returned 403 

### ISSUE THREAD

**Issue by Dark-Kernel** [termux-pacman/pacman-for-termux#19]
![image](https://github.com/termux-pacman/pacman-for-termux/assets/89197795/759bad30-13b1-45b5-955d-946b0e3d9530)

Here is the problem,
I have done everything told in the instructions [here](https://wiki.termux.com/wiki/Switching_package_manager)
Though I am getting this issue, Please anyone helps with this?

Thank you.

**Comment by Maxython** [comment]
Duplication of https://github.com/termux-pacman/termux-packages/issues/9

We apologize for the inconvenience, but at the moment all the latest events will be cleared up there.
